In [2]:
danhsach1 = [1., 3.]
danhsach2 = [5., 7.]
danhsach = danhsach1 + danhsach2
print(danhsach)  

danhsach_gapdoi = 2 * danhsach
print(danhsach_gapdoi)  

print(danhsach * 2)  


[1.0, 3.0, 5.0, 7.0]
[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]
[1.0, 3.0, 5.0, 7.0, 1.0, 3.0, 5.0, 7.0]


In [3]:
mon_hoc = ["ToanCC", "DSTT", "ToanRR", "LaptrinhCB"]
thu_tu = [2, 3, 4, 1]
diem_so = [10, 9, 8, 7]
anh_xa = zip(thu_tu, mon_hoc, diem_so)
print(anh_xa)  # <zip object at ...> (memory address will vary)

tap_hop = set(anh_xa)
print(tap_hop)  # {(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)}

# Note: anh_xa is consumed after creating tap_hop, so we need to recreate it
anh_xa = zip(thu_tu, mon_hoc, diem_so)
lay_TT, lay_monhoc, lay_diem = zip(*anh_xa)
print(lay_monhoc)  # ('ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB')

{(2, 'ToanCC', 10), (3, 'DSTT', 9), (4, 'ToanRR', 8), (1, 'LaptrinhCB', 7)}
('ToanCC', 'DSTT', 'ToanRR', 'LaptrinhCB')


In [5]:
from itertools import chain

tap_sinh = list(chain(range(4), range(5, 10), range(15, 20)))
print(tap_sinh)

tap = list(zip(tap_sinh, range(0, len(tap_sinh))))
print(tap)

moi_tap = list(zip(range(4), range(7, 12), reversed(range(11))))
print(moi_tap)

[0, 1, 2, 3, 5, 6, 7, 8, 9, 15, 16, 17, 18, 19]
[(0, 0), (1, 1), (2, 2), (3, 3), (5, 4), (6, 5), (7, 6), (8, 7), (9, 8), (15, 9), (16, 10), (17, 11), (18, 12), (19, 13)]
[(0, 7, 10), (1, 8, 9), (2, 9, 8), (3, 10, 7)]


In [6]:
from sympy import Symbol
x = Symbol('x') 
f = x + x + x + 2 
print(f)  

3*x + 2


In [ ]:
from sympy import Symbol

a = Symbol('Noi')
b = Symbol('Chim')
print(3*b + 7*a)  

print(a.name)  
print(b.name)  

3*Chim + 7*Noi
Noi
Chim


In [8]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')
s = x*y + y*x
print(s)  

p = x*(x + 2*x)
print(p)  

p = (x + 2)*(y + 3) + (x + 2)*(x - 3)
print(p)  

p = x*(-x + 2*x - x)
print(p)  

p = (x + 2)*(y + 3)
print(p.expand())  

2*x*y
3*x**2
(x - 3)*(x + 2) + (x + 2)*(y + 3)
0
x*y + 3*x + 2*y + 6


In [9]:
from sympy import Symbol, factor, expand

x = Symbol('x')
y = Symbol('y')

bieuthuc = x**3 - y**3
print(factor(bieuthuc))  # (x - y)*(x**2 + x*y + y**2)

bieuthuc = (x - y)*(x**2 + x*y + y**2)
print(expand(bieuthuc))  # x**3 - y**3

(x - y)*(x**2 + x*y + y**2)
x**3 - y**3


In [10]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
print(bieuthuc)  # x**2 - x*y + y**2

giatri = bieuthuc.subs({x: 3, y: 2})
print(giatri)  # 5

print(x)  # x
print(y)  # y

x**2 - x*y + y**2
7
x
y


In [11]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y

giatri = bieuthuc.subs({x: 3, y: x})
print(giatri)

giatri = bieuthuc.subs({x: y, y: 3})
print(giatri)

giatri = bieuthuc.subs({y: x}).subs({x: 3})
print(giatri)

x**2 - 3*x + 9
9
9


In [12]:
from sympy import Symbol

x = Symbol('x')
y = Symbol('y')
bieuthuc = x*x - x*y + y*y
print(bieuthuc)

bieuthuc_moi = bieuthuc.subs({x: 1 - y})
print(bieuthuc_moi)

from sympy import simplify
dongian = simplify(bieuthuc_moi)
print(dongian)

from sympy import sin, cos
x = Symbol('x')
y = Symbol('y')
bt = sin(x)*cos(y) + cos(x)*sin(y)
bt_moi = simplify(bt)
print(bt_moi)

x**2 - x*y + y**2
y**2 - y*(1 - y) + (1 - y)**2
3*y**2 - 3*y + 1
sin(x + y)


In [14]:
import numpy as np

vec1 = np.array([1., 3., 5.])
print(vec1 * 2)

print(vec1 * vec1)

print(vec1 / 2)

print(vec1 + vec1)

vec2 = np.array([2., 4.])
# print(vec1 + vec2)

vec3 = np.array([2., 4., 6.])
print(vec1 + vec3)

print(vec1 / vec3)

print(vec1 * vec3)

print(2 * vec1 + 5 * vec3)

[ 2.  6. 10.]
[ 1.  9. 25.]
[0.5 1.5 2.5]
[ 2.  6. 10.]
[ 3.  7. 11.]
[0.5        0.75       0.83333333]
[ 2. 12. 30.]
[12. 26. 40.]


In [15]:
import numpy as np

vec3 = np.array([2., 4., 6.])
print(vec3[2])

vec4 = np.linspace(0, 20, 5)
print(vec4)

vec5 = np.zeros(5)
print(vec5)

vec6 = np.ones(5)
print(vec6)

vec7 = np.empty(5)
print(vec7)

print(np.random.random(5))

6.0
[ 0.  5. 10. 15. 20.]
[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1.]
[0.48098368 0.09912562 0.25790112 0.91322491 0.35488916]


In [16]:
import numpy as np

v = np.array([1., 3., 5.])
print(np.sum(v))

print(v.shape)

print(v.transpose())

v1 = v[:2]
print(v1)

v[0] = 5
print(v)

print(v1)

# v1[:2] = [1., 2., 3.]  # Error: Expected 2 elements, got 3

v1[:2] = [1., 2.]
print(v)

v3 = 2 * v[:2] + v1 * 3
print(v3)

v1 = [4, 6]
print(v3)

print(v)

print(v + 10.0)

print(np.sqrt(v))

print(np.cos(v))

print(np.sin(v))

v1 = np.array([1., 2.])
v3 = np.array([11., 16.])
print(np.dot(v1, v3))

print(v1.dot(v3))

print(v3.dot(v1))

9.0
(3,)
[1. 3. 5.]
[1. 3.]
[5. 3. 5.]
[5. 3.]
[1. 2. 5.]
[ 5. 10.]
[ 5. 10.]
[1. 2. 5.]
[11. 12. 15.]
[1.         1.41421356 2.23606798]
[ 0.54030231 -0.41614684  0.28366219]
[ 0.84147098  0.90929743 -0.95892427]
43.0
43.0
43.0
