In [1]:
import numpy as np

D = np.array([[1, 2], [3, 4]])

try:
    np.copyto(E, D)
except NameError as e:
    print("Lỗi:", e)

E = np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print(E)


Lỗi: name 'E' is not defined
[[1 2]
 [3 4]]


In [2]:
import numpy as np

x = np.array([['a','b'],['c','d']])
y = 'x'
C = np.array([[str(x), y], ['1', '2']])
print(C)


[["[['a' 'b']\n ['c' 'd']]" 'x']
 ['1' '2']]


In [3]:
import numpy as np

try:
    A = np.matrix([[[1,2],[3,4]],[[5,6],[7,8]]])
except Exception as e:
    print("Lỗi:", e)

A = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(A)


Lỗi: matrix must be 2-dimensional
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [4]:
from numpy import matlib 
G = matlib.identity(5)   # cú pháp: matlib.identity(n) 
print (G)
H = matlib.randn(3,2) # cú pháp: matlib.randn(*args) 
print(H)
K = matlib.zeros([4,4])  #  cú pháp: matlib.zeros(shape) 
print(K) 

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[ 0.37200929  1.53899515]
 [ 0.21432316  0.19430245]
 [ 0.08509969 -0.39778286]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
import numpy as np

c = [3, 7, 15, 1, 292, 1, 1, 1, 2, 1, 3, 1, 14, 2]  # có thể thay đổi để thử dãy khác

M = np.asmatrix([[1, 2], [3, 4]])  # khởi tạo ma trận, sẽ bị thay ngay nên giá trị ban đầu không quan trọng

for i in range(len(c)):
    ci = np.asmatrix([[1, 1], [1, 0]])
    ci[0, 0] = c[i]
    if i == 0:
        M = ci
    else:
        M = M.dot(ci)

print(M)
print(M[0, 0] / M[1, 0])  # in số Pi theo dãy liên phân số


[[165707065  80143857]
 [ 52746197  25510582]]
3.1415926535897936


BÀI TẬP CHƯƠNG 5

In [6]:
import numpy as np

def bpcuctieu(a):
    b = []
    o1 = []
    for i in range(len(a)):
        o1.append(1.0)
        b.append(i * 1.0)
    x = np.array([o1, b])
    u = np.dot(x, x.T)
    y = np.array(a)
    from numpy import linalg
    u_1 = np.linalg.inv(u)
    v = np.dot(u_1, x)
    A = np.dot(v, y)
    return A

dulieu = [10.0, 8, 7, 5, 2]
A = bpcuctieu(dulieu)
print("Phương trình: y = {:.1f} + {:.1f}·x".format(A[0], A[1]))


Phương trình: y = 10.2 + -1.9·x
