BÀI TẬP TRÊN LỚP

In [ ]:
#bt1
import numpy as np
from scipy import linalg, sparse
D = np.asmatrix([ [3,4], [5,6] ])
print(D)

[[3 4]
 [5 6]]


In [ ]:
#bt2
C=np.asmatrix(np.random.random((5,7)))
print(C)

[[0.21312659 0.46035668 0.83827075 0.50018069 0.57961424 0.1185159
  0.15941423]
 [0.67750938 0.34158565 0.72314727 0.03276693 0.09435749 0.59832191
  0.71322665]
 [0.72465079 0.07396125 0.9358717  0.88866176 0.61502148 0.51584774
  0.7304909 ]
 [0.82213172 0.10322254 0.00412612 0.95788432 0.39772213 0.23526798
  0.61705198]
 [0.22233169 0.98905274 0.96754972 0.88734806 0.66145728 0.431495
  0.23648363]]


In [ ]:
#bt3
A=np.asmatrix(np.random.random((2,2)))
print(A)

[[0.78559293 0.23869631]
 [0.8786127  0.98430641]]


In [ ]:
#bt4,5
b = np.array([(1+5j, 2j, 3j),(4, 5,6)])
B = np.asmatrix(b)
print(b)
print(B)

[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
[[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [ ]:
#bt6
print(A.T)
print(A.I)

[[0.78559293 0.8786127 ]
 [0.23869631 0.98430641]]
[[ 1.74664082 -0.42356396]
 [-1.55908851  1.39402595]]


In [ ]:
#bt7
linalg.inv(A)
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M)
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [ ]:
#bt8
M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper)

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [ ]:
#bt9
M = np.array([[-1,3,2],[0,-
2,1],[1,5,-2]])
v_diag = np.diag(M) #vectorđường chéo
print (v_diag)

[-1 -2 -2]


In [ ]:
#bt10
M_diag = np.diag(v_diag)
print (M_diag)

[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


In [ ]:
#Bài tập dẫn nhập
import sympy as sp
x = sp.Symbol('x')
y = sp.Symbol('y')
z = sp.Symbol('z')
f=sp.solve([x*x + 2 - 6,y - 1 - 6,x*z - 1,2*x*x - 8,z*z + 4 - 5,y - z - 8], [x, y, z])
print(f)

[]


In [ ]:
x = [1, 2, 3]
y = [1, 2, 3]
print(all([x[i] == y[i] for i in range(len(x))]))  # True

y = [1, 2, 4]
print(all([x[i] == y[i] for i in range(len(x))]))  # False


True
False


In [ ]:
import numpy as np

print(np.array_equal([1, 2], [1, 2]))  # True
print(np.array_equal(np.array([1, 2]), np.array([1, 2])))  # True


True
True


In [ ]:
A = np.reshape(np.arange(36.0), (6,6))
print(A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [ ]:
I6 = np.identity(6)
print(I6)


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
A=A.size
print(A)

36


In [ ]:
A = np.reshape(np.arange(36.0), (6,6))
print(A)




[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [ ]:
I6 = np.identity(6)
print(I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
a=A.size
print(a)

36


In [ ]:
a=np.matrix.diagonal(A)
print(a)

[ 0.  7. 14. 21. 28. 35.]


In [ ]:
A = A + I6
print(A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print(C)

[ 71. 198. 325. 452. 579. 706.]


In [ ]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print(D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


In [ ]:
E = A.dot(D.T)
print(E)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [ ]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print(F)
print(G)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]
[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


In [ ]:
a=np.linalg.inv(A)
print(a)

[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]


In [ ]:
a=np.linalg.inv(np.linalg.inv(A))
print(a)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


In [ ]:
import numpy as np

A = np.array([[1, 1], [1, 0]])
b = np.array([1, 0])
n = 10

for i in range(n):
    b = A.dot(b)
    print(b)


[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


In [ ]:
import sympy as sp
from sympy import Symbol, solve


x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4 + 610 - 450 - x1
pt2 = x1 + 400 - x2 - 640
pt3 = x2 + 600 - x3
pt4 = x3 - x4 - 520
nghiem = solve((pt1, pt2, pt3, pt4))
print(nghiem)


{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}
