bài tạp trên lớp

In [4]:
import numpy as np

F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
F = np.eye(3, k=-1)  
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [10]:

import numpy as np
from scipy import linalg

A = np.matrix([[4, 3], [2, 6]])
C = np.asmatrix(np.random.random((3, 3)))

print(np.linalg.matrix_rank(C))
print(A.I)
print(linalg.inv(A))
print(linalg.det(A))
print(A.T)
print(A.H)


3
[[ 0.33333333 -0.16666667]
 [-0.11111111  0.22222222]]
[[ 0.33333333 -0.16666667]
 [-0.11111111  0.22222222]]
18.0
[[4 2]
 [3 6]]
[[4 2]
 [3 6]]


In [21]:
A = np.array([[4, 3],[2, 6]])
b = np.array([10, 16])
a = np.array([10, 16])
F = np.array([10, 15])
E = np.array([10, 55])
print(linalg.solve(A, b) )
E = np.asmatrix(a).T
print(E)
print(linalg.lstsq(F, E) )

[0.66666667 2.44444444]
[[10]
 [16]]


ValueError: Input array a should be 2D

In [22]:
import numpy as np
from scipy import linalg

# Hệ phương trình A x = b
A = np.array([[4, 3], [2, 6]])
b = np.array([10, 16])
print("Nghiệm hệ A x = b:")
print(linalg.solve(A, b))

# Tạo vector cột E từ a
a = np.array([10, 16])
E = np.asmatrix(a).T
print("\nVector cột E:")
print(E)

# Tạo F đúng dạng (2D)
F = np.array([[1, 2],
              [3, 4]])

# Giải hệ dư phương trình F x ≈ E
x, residuals, rank, s = linalg.lstsq(F, E)
print("\nNghiệm gần đúng (least squares):")
print(x)


Nghiệm hệ A x = b:
[0.66666667 2.44444444]

Vector cột E:
[[10]
 [16]]

Nghiệm gần đúng (least squares):
[[-4.]
 [ 7.]]


In [23]:
import numpy as np
from scipy import linalg

A = np.array([[1, 2],[3, 4]])

D = np.array([[5, 6],[7, 8]])

print(np.add(A, D))
print(np.subtract(A, D))
print(np.divide(A, D))
print(A @ D)
print(np.multiply(D, A))
print(np.dot(A, D))
print(np.vdot(A, D))
print(linalg.expm(A))
print(linalg.logm(A))


[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
70
[[ 51.9689562   74.73656457]
 [112.10484685 164.07380305]]
[[-0.35043981+2.39111795j  0.92935121-1.09376217j]
 [ 1.39402681-1.64064326j  1.04358699+0.7504747j ]]


In [24]:
import numpy as np

A = np.array([[0, 1], [1, 0]])
print(A)


[[0 1]
 [1 0]]


In [25]:
temp = A.dot(A)
print(temp)


[[1 0]
 [0 1]]


In [27]:
k= 6 
for i in range(k-1): 
    
    temp = temp.dot(A) 
    print (temp) 
    print('---')      

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


In [28]:
B = np.array([ [0,-1], [-1,0]]) 
print(B)

[[ 0 -1]
 [-1  0]]


In [29]:
temp = B.dot(B)     # tính toan lần thứ 1 
print(temp) 

[[1 0]
 [0 1]]


In [30]:
k= 5 
for i in range(k-1): 
    temp = temp.dot(B) 
    print (temp) 
    print('---')  

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


In [31]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ]) 
print(C)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [32]:
temp = C.dot(C)     # tính toan lần thứ 1 
print(temp)

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [34]:
k= 1000 
for i in range(k-1): 
    temp = temp.dot(C) 
    print(temp) 

[[1.    0.    0.   ]
 [0.    0.125 0.75 ]
 [0.    0.    0.125]]
[[1.     0.     0.    ]
 [0.     0.0625 0.5   ]
 [0.     0.     0.0625]]
[[1.      0.      0.     ]
 [0.      0.03125 0.3125 ]
 [0.      0.      0.03125]]
[[1.       0.       0.      ]
 [0.       0.015625 0.1875  ]
 [0.       0.       0.015625]]
[[1.        0.        0.       ]
 [0.        0.0078125 0.109375 ]
 [0.        0.        0.0078125]]
[[1.         0.         0.        ]
 [0.         0.00390625 0.0625    ]
 [0.         0.         0.00390625]]
[[1.         0.         0.        ]
 [0.         0.00195312 0.03515625]
 [0.         0.         0.00195312]]
[[1.000000e+00 0.000000e+00 0.000000e+00]
 [0.000000e+00 9.765625e-04 1.953125e-02]
 [0.000000e+00 0.000000e+00 9.765625e-04]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 4.88281250e-04 1.07421875e-02]
 [0.00000000e+00 0.00000000e+00 4.88281250e-04]]
[[1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 2.44140625e-04 5.85937500e-03]
 [0.

In [35]:
k= 1000 
for i in range(k-1): 
    temp = temp.dot(C) 
    print(temp) 

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.33315905e-302 4.67565073e-299]
 [0.00000000e+000 0.00000000e+000 2.33315905e-302]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 1.16657952e-302 2.34015852e-299]
 [0.00000000e+000 0.00000000e+000 1.16657952e-302]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.83289762e-303 1.17124584e-299]
 [0.00000000e+000 0.00000000e+000 5.83289762e-303]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 2.91644881e-303 5.86206210e-300]
 [0.00000000e+000 0.00000000e+000 2.91644881e-303]]
[[1.0000000e+000 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 1.4582244e-303 2.9339475e-300]
 [0.0000000e+000 0.0000000e+000 1.4582244e-303]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 7.29112202e-304 1.46843197e-300]
 [0.00000000e+000 0.00000000e+000 7.29112202e-304]]
[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 3.64556101e-304 

In [36]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]]) 
MM = M.dot(M)   # tính M2, nghĩa là M2 
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [37]:
MM = M.dot(M)   # tính M3 
print (MM)

[[0.7  0.45]
 [0.3  0.55]]


In [38]:
for i in range(100):   # tính các M^ khác. 
    MM = MM.dot(M) 
    print (MM)   # kết luận xu hướng của  

[[0.65  0.525]
 [0.35  0.475]]
[[0.625  0.5625]
 [0.375  0.4375]]
[[0.6125  0.58125]
 [0.3875  0.41875]]
[[0.60625  0.590625]
 [0.39375  0.409375]]
[[0.603125  0.5953125]
 [0.396875  0.4046875]]
[[0.6015625  0.59765625]
 [0.3984375  0.40234375]]
[[0.60078125 0.59882813]
 [0.39921875 0.40117187]]
[[0.60039063 0.59941406]
 [0.39960938 0.40058594]]
[[0.60019531 0.59970703]
 [0.39980469 0.40029297]]
[[0.60009766 0.59985352]
 [0.39990234 0.40014648]]
[[0.60004883 0.59992676]
 [0.39995117 0.40007324]]
[[0.60002441 0.59996338]
 [0.39997559 0.40003662]]
[[0.60001221 0.59998169]
 [0.39998779 0.40001831]]
[[0.6000061  0.59999084]
 [0.3999939  0.40000916]]
[[0.60000305 0.59999542]
 [0.39999695 0.40000458]]
[[0.60000153 0.59999771]
 [0.39999847 0.40000229]]
[[0.60000076 0.59999886]
 [0.39999924 0.40000114]]
[[0.60000038 0.59999943]
 [0.39999962 0.40000057]]
[[0.60000019 0.59999971]
 [0.39999981 0.40000029]]
[[0.6000001  0.59999986]
 [0.3999999  0.40000014]]
[[0.60000005 0.59999993]
 [0.39999995 0.

In [40]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]]) 
P, L, U = linalg.lu(M)    # lệnh lina.lu sẽ tách ma trận M thành 3 ma trận P, L và U 
print (P) 

print (L) 

print (U)

print( L.dot(U) )

[[1. 0.]
 [0. 1.]]
[[1.   0.  ]
 [0.25 1.  ]]
[[0.8   0.3  ]
 [0.    0.625]]
[[0.8 0.3]
 [0.2 0.7]]


In [41]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]]) 
temp = A.dot(A)    # lúc này temp =  
print(temp) 

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [42]:
temp = temp.dot(A)    # lúc này temp =  
print(temp) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [43]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]]) 
sumA = A 
temp = A.dot(A) 
k = 3 
sumA = sumA + temp 
for i in range(1, k-1): 
    temp = temp.dot(A) 
    sumA = sumA + temp 
    print (temp) 
    print (sumA) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


bài tập về nhà