In [2]:
import numpy as np 
a = np.array([1,2,3]) 
b = np.array([4,5,6]) 
tich = np.inner(a,b)  # tích vô hướng 
print (tich)
print(np.dot(a,b))

32
32


In [3]:
import numpy as np 
a = np.array([1,2,-3]) 
print(np.linalg.norm(a))

3.7416573867739413


In [5]:
a = np.array([1,2,-3]) 
print(np.linalg.norm(a,1) )

6.0


In [10]:
import math
import numpy as np
from scipy import linalg 
a = np.array([1, 2, -3])

def chuan(a, p):
    tong = 0
    for x in a:
        tong = tong + abs(x) ** p
    ketqua = math.pow(tong, 1.0 / p)
    return ketqua

print(chuan(a, 1))
print(np.linalg.norm(a, 1))
print(chuan(a, 2))
print(np.linalg.norm(a, 2))
print(chuan(a, 3))
print(np.linalg.norm(a, 3))
print(chuan(a, 1000))
print(np.linalg.norm(a, 1000))
print(linalg.norm(a))
print(linalg.norm(a, 100))
print(linalg.norm(a, 1000))



6.0
6.0
3.7416573867739413
3.7416573867739413
3.3019272488946263
3.3019272488946263
1.0442214818467515
inf
3.7416573867739413
3.0
inf


In [11]:
import sympy as sym 
x, y = sym.symbols('x y') 
xy = sym.Matrix([x,y])
A = sym.Matrix([[1, -68],[1,1]]) 
v = sym.Matrix([0, 1])                             
nghiem = sym.solve([A*xy-v])   
print(sym.pretty(nghiem))

⎧   68         ⎫
⎨x: ──, y: 1/69⎬
⎩   69         ⎭


In [12]:
import sympy 
x, y, Lambda = sympy.symbols('x y Lambda') 
I = sympy.eye(2) 

A = sympy.Matrix([[2,3],[3,-6]]) 
phuongtrinh = sympy.Eq(sympy.det(Lambda*I-A), 0) 
nghiem = sympy.solve(phuongtrinh) 
print([sympy.N(phantu,4) for phantu in nghiem])
print (sympy.pretty(nghiem)) 

[-7.000, 3.000]
[-7, 3]


In [15]:
import numpy as np 
A = np.array([[2,3],[3,-6]]) 
D = np.array([[-7,0],[0,3]]) 
P = np.array([[-1.0/3, 3],[1,1]]) 
from numpy import linalg 
from numpy import linalg as LA 
P1 = LA.inv(P)   # tính giá trị nghịch đảo của P 
print (P1)
print(A.dot(P) )
print(P.dot(D))
F = P @ (D ** 1000) @ P1
print(F)
print (D **2) 

[[-0.3  0.9]
 [ 0.3  0.1]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 2.33333333  9.        ]
 [-7.          3.        ]]
[[ 5.03503397e+18  3.50482117e+18]
 [ 3.50482117e+18 -4.31115581e+18]]
[[49  0]
 [ 0  9]]


BÀI TẬP CHƯƠNG 6

Câu 1: [Trắc nghiệm]
a. >>> mag = np.sqrt(a.dot(a))  

In [18]:
# Câu 2: Sinh viên hãy viết các chương trình tính toán theo các công thức:
# a
import numpy as np
import math
def vector_distance(u, v):
    return np.linalg.norm(u - v)
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print(vector_distance(u, v))
# b

def vector_angle(u, v):
    dot_product = np.dot(u, v)
    norm_u = np.linalg.norm(u)
    norm_v = np.linalg.norm(v)
    cos_theta = dot_product / (norm_u * norm_v)
    # Ép giá trị vào [-1, 1] để tránh lỗi do sai số số học
    cos_theta = np.clip(cos_theta, -1.0, 1.0)
    return math.acos(cos_theta)
print(vector_angle(u, v))
# c
def projection(u, v):
    scalar = np.dot(u, v) / np.dot(v, v)
    return scalar * v
print(projection(u, v))

5.196152422706632
0.2257261285527342
[1.66233766 2.07792208 2.49350649]
